server:
    port: 8900

spring:
    application:
        name: config
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:native}
    security:
        user:
            name: ${CONFIG_SERVER_USERNAME:config-user}
            password: ${CONFIG_SERVER_PASSWORD:config-password}
    cloud:
        config:
            server:
                native:
                    search-locations: ${CONFIG_SEARCH_LOCATIONS:file:./config}
