server:
    port: 8900

spring:
    application:
        name: config
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:native}
    cloud:
        config:
            server:
                native:
                    search-locations: ${CONFIG_SEARCH_LOCATIONS:file:/config-repo}
