server:
  port: 8901

spring:
    application:
        name: identity
    config:
        import: optional:file:.env[.properties]
    cloud:
        config:
            enabled: false
            uri: ${CONFIG_SERVER_URI:http://localhost:8900}
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/linkyou?currentSchema=public}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:nerosoft.8888}
        driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    jpa:
        hibernate:
            ddl-auto: update
            dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        show-sql: true
    data:
        redis:
            url: ${REDIS_URL:redis://localhost:6379}
        mongodb:
            uri: ${MONGO_URI:mongodb://localhost:27017/linkyou}

external-auth:
    redirect-uri: "https://theurl.io/auth/callback"
    google:
        client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
        client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
    github:
        client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
        client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
    facebook:
        client-id: ${FACEBOOK_CLIENT_ID:your-facebook-client-id}
        client-secret: ${FACEBOOK_CLIENT_SECRET:your-facebook-client-secret}
    microsoft:
        client-id: ${MICROSOFT_CLIENT_ID:your-microsoft-client-id}
        client-secret: ${MICROSOFT_CLIENT_SECRET:your-microsoft-client-secret}

logging:
    file:
        path: logs
    level:
        io.theurl.identity: debug
        org.springframework: info
        root: info
