server:
    port: 8902

spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
    application:
        name: message
    config:
        import: optional:file:.env[.properties]
    cloud:
        config:
            enabled: false
            uri: ${CONFIG_SERVER_URI:http://localhost:8900}
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/linkyou?currentSchema=public}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    jpa:
        hibernate:
            ddl-auto: update
            dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        show-sql: true
    data:
        redis:
            url: ${REDIS_URL:redis://localhost:6379}
        mongodb:
            uri: ${MONGO_URI:mongodb://localhost:27017/linkyou}
    rabbitmq:
        host: ${RABBITMQ_HOST:127.0.0.1}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:guest}
        password: ${RABBITMQ_PASSWORD:guest}
